### ISSUE TITLE
考虑支持批量处理吗？thanks~

### ISSUE THREAD

**Issue by meichiny** [Forgot-Dream/STS-Bcut#1]
考虑加入批量处理音频转多个字幕文件吗？

**Comment by Forgot-Dream** [comment]
> 考虑加入批量处理音频转多个字幕文件吗？

可以加的，但是什么时候能写完就不确定了，我尽量有空就写

**Comment by meichiny** [comment]
> 

期待。谢谢😀

**Comment by Forgot-Dream** [comment]
已经实现，并且发布至[1.0.1](https://github.com/Forgot-Dream/STS-Bcut/releases/tag/1.0.1)版本。
