### ISSUE TITLE
转换的音频会自动删除吗?

### ISSUE THREAD

**Issue by uzcool** [Forgot-Dream/STS-Bcut#2]
如题..可以加个选项不自动删吗..

**Comment by Forgot-Dream** [comment]
确实会自动删除，可以添加选项，但是这样子就需要写入一个配置文件了。我慢慢写吧。

**Comment by Forgot-Dream** [comment]
功能已完成 [1.0.3](https://github.com/Forgot-Dream/STS-Bcut/releases/tag/1.0.3) 版本已发布
