### ISSUE TITLE
Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by hmm5555** [Forgot-Dream/STS-Bcut#5]
解析文本会出现的错误 指标超出异常了at STS_Bcut.src.BcutAPI.QueryResult() 
Bcut\src\BcutAPI.cs:line 192
at STS_Bcut.src.BcutAPI.Run()
\BcutAPI.cs:line 88
 at STS_Bcut.src.Common.STSTask.<Run>b__28_0
\STS-Bcut\src\Common\STSTask.cs:line 86
![1703674053891](https://github.com/Forgot-Dream/STS-Bcut/assets/65001058/257216e7-4f4a-4a2a-8d76-f947d1cc062d)

**Comment by Forgot-Dream** [comment]
能麻烦提供一下解析错误的文本吗，我这边目前无法复现。

**Comment by hmm5555** [comment]
![image](https://github.com/Forgot-Dream/STS-Bcut/assets/65001058/2503b1e4-0500-47ee-9ea0-2c2fe31f577e)
![74631a86eb312dbca8d31c3524e3e42](https://github.com/Forgot-Dream/STS-Bcut/assets/65001058/1333fc35-28c2-4a58-a617-76ffb473570d)

**Comment by hmm5555** [comment]
![e27860262c06ce764ef1a321b47676d](https://github.com/Forgot-Dream/STS-Bcut/assets/65001058/d1997b1e-c2c5-467f-acce-09c671402cad)
reply的值后续跳到参数超出异常

**Comment by hmm5555** [comment]
请求的json
![1703677306096](https://github.com/Forgot-Dream/STS-Bcut/assets/65001058/f65171cd-d45b-43f2-82f9-1bc4c099aeb4)

**Comment by Forgot-Dream** [comment]
`state`字段出现了返回`0`这一个代表意思不明的选项，我处理一下吧，但是是tempfix。我可能要之后才能确定这个值的意思。您有相关猜测可以在此issue下追加。
https://github.com/Forgot-Dream/STS-Bcut/blob/c32f1a7677c87925e178fa397fe7afd391ac3e89/src/APIDataStruct.cs#L52-L58

**Comment by hmm5555** [comment]
ok

**Comment by Forgot-Dream** [comment]
https://github.com/Forgot-Dream/STS-Bcut/actions/runs/7337999835 尝试一下最新commit能不能正常使用。
