### ISSUE TITLE
提示请求出错

### ISSUE THREAD

**Issue by diguawl** [Forgot-Dream/STS-Bcut#7]
视频转换出音频之后，提示请求出错！
![微信截图_20240702105818](https://github.com/Forgot-Dream/STS-Bcut/assets/49666880/1c408cdf-fc82-4563-b1d0-4db06c75fb10)

**Comment by Forgot-Dream** [comment]
目前（2024.7.2 11:00前后）B站服务器出现大规模不可用情况，请等待B站方面解决。
